package com.xworkz.collection.Airport;

import com.xworkz.collection.ListCRUD.FlowerDAO;
import com.xworkz.collection.ListCRUD.FlowerDTO;

public class TestAirport {
	public static void main(String[] args) {

		AirportDTO dto = new AirportDTO();
		dto.setFName("AirIndia");
		dto.setFtimings("12.00pm");
		dto.setCapacity((byte)25);
		dto.setDestination("NewDelhi");
		dto.setNoOfPass((byte)12);
		
		AirportDTO dto1 = new AirportDTO();
		dto1.setFName("Indigo");
		dto1.setFtimings("1.40am");
		dto1.setCapacity((byte)20);
		dto1.setDestination("Mumbai");
		dto1.setNoOfPass((byte)18);
		
		
		AirportDAO dao = new AirportDAO();
		dao.add(dto);
		dao.add(dto1);
		dao.printAll(); 
		System.out.println();
		
		System.out.println("data updated");
		AirportDTO update=dao.updateFtimingsbyFName("2.10am", "Indigo");
		System.out.println(update);
		
		System.out.println("data generated by  noOfPass");
		AirportDTO  get = dao.getBynoOfPass((byte)12);
		System.out.println(get);
		
		
		AirportDTO delete=dao.deleteByDestination("Mumbai");
		System.out.println(delete);
		System.out.println();
		dao.printAll();
		
		
	}
	

	
}
